--- 
changelog:
  - 
    changes: 
      - 
        text: "Correct null check for signal callback"
        type: bug
    date: Mar 10, 20  
    version: v4.8.1
  - 
    changes: 
      - 
        text: "Token Management System - Client end"
        type: improvement
    date: Feb 18, 20  
    version: v4.8.0
  - 
    changes: 
      - 
        text: "HereNow Deserialization Error fix"
        type: improvement
    date: Feb 5, 20  
    version: v4.7.3
  - 
    changes: 
      - 
        text: "Heartbeat query param in Presence heartbeat call"
        type: bug
      - 
        text: "Presence Heartbeat defaults to 300"
        type: improvement
    date: Jan 16, 20  
    version: v4.7.2
  - 
    changes: 
      - 
        text: "Objects Filtering"
        type: improvement
    date: Jan 6, 20  
    version: v4.7.1   
  - 
    changes: 
      - 
        text: "APNS2"
        type: improvement
      - 
        text: "Push payload helper class"
        type: improvement
    date: Dec 24, 19  
    version: v4.7.0  
  - 
    changes: 
      - 
        text: "Message Actions added missing TotalCount, Next, Prev for Get Users/Spaces, Manage/Get Members/Memberships"
        type: improvement
      - 
        text: "Return types of Start and End in PNGetMessageActionsMore changed to long"
        type: improvement
    date: Nov 22, 19  
    version: v4.6.0  
  - 
    changes: 
      - 
        text: "Message Actions"
        type: improvement
      - 
        text: "Fetch with Message Actions"
        type: improvement
    date: Nov 21, 19  
    version: v4.5.0  
  - 
    changes: 
      - 
        text: "Objects"
        type: improvement
    date: Nov 8, 19  
    version: v4.4.0  
  - 
    changes: 
      - 
        text: "Signals"
        type: improvement
      - 
        text: "IncludeMeta in History and Fetch"
        type: improvement
    date: Oct 10, 19  
    version: v4.3.0  
  - 
    changes: 
      - 
        text: "Presence Timeout cannot be lower than 20"
        type: improvement
      - 
        text: "PNPresenceEventResult.State property not populated in callback"
        type: bug
    date: Jun 4, 19  
    version: v4.2.1  
  - 
    changes: 
      - 
        text: "Message Counts simplification (Breaking changes from the previous version)."
        type: improvement
    date: Mar 13, 19  
    version: v4.2.0
  - 
    changes: 
      - 
        text: "Message Counts API"
        type: improvement 
    date: "Mar 5, 19"
    version: v4.1.1
  - 
    changes: 
      - 
        text: "BREAKING CHANGE: Fixed a typo by renaming the `event` from `SusbcribeCallback` to `SubscribeCallback` and the `EventArgs` from `SusbcribeEventEventArgs` to `SubscribeEventEventArgs` "
        type: improvement 
    date: "Feb 18, 19"
    version: v4.1.0
  - 
    changes: 
      - 
        text: "Presence Heartbeat call delays itself when a Subscribe call precedes it"
        type: improvement
      - 
        text: "Heartbeats per channel"
        type: feature
      - 
        text: "QueryParams in all API calls"
        type: feature
      - 
        text: "User Exceptions Fix"
        type: improvement      
      - 
        text: "Leave callback message exception fix"
        type: bug       
    date: "Jan 9, 19"
    version: v4.0.5
  - 
    changes: 
      - 
        text: "UnityPackage reorganization"
        type: improvement
    date: "Nov 13, 18"
    version: v4.0.4
  - 
    changes: 
      - 
        text: "Travis update for UnityPackage"
        type: improvement
    date: "Nov 12, 18"
    version: v4.0.3
  - 
    changes: 
      - 
        text: "Delete Messages Fix"
        type: improvement
    date: "Aug 23, 18"
    version: v4.0.2
  - 
    changes: 
      - 
        text: "Integration tests fixes"
        type: improvement
    date: "Mar 8, 18"
    version: v4.0.1
  - 
    changes: 
      - 
        text: "Here Now Refresh"
        type: improvement
    date: "Feb 28, 18"
    version: v4.0-rc2
  - 
    changes: 
      - 
        text: Cleanup
        type: improvement
    date: "Jan 22, 18"
    version: v4.0-beta6
  - 
    changes: 
      - 
        text: "Logging enhancements"
        type: improvement
    date: "Jan 18, 18"
    version: v4.0-beta5
  - 
    changes: 
      - 
        text: Cleanup
        type: improvement
    date: "Jan 16, 18"
    version: v4.0-beta4
  - 
    changes: 
      - 
        text: "Windows Universal compatibility"
        type: improvement
    date: "Jan 11, 18"
    version: v4.0-beta3
  - 
    changes: 
      - 
        text: "Leave fixes"
        type: improvement
    date: "Dec 26, 17"
    version: v4.0-beta2
  - 
    changes: 
      - 
        text: "All new PubNub Unity SDK"
        type: improvement
    date: "Dec 11, 17"
    version: v4.0-beta1
  - 
    changes: 
      - 
        text: "Presence delta intervals"
        type: improvement
    date: "Dec 18, 17"
    version: v3.7.10
  - 
    changes: 
      - 
        text: "Unity UWP compatibility"
        type: improvement
    date: "Aug 8, 17"
    version: v3.7.9
  - 
    changes: 
      - 
        text: "Presence delta intervals"
        type: improvement
    date: "Mar 31, 17"
    version: v3.7.8
  - 
    changes: 
      - 
        text: "Region check in Timetoken dictionary"
        type: bug
      - 
        text: "Prefix UUID with 'pn-'"
        type: improvement
    date: "Feb 20, 17"
    version: v3.7.7
  - 
    changes: 
      - 
        text: "Fixed user state issue for other UUID"
        type: bug
    date: "Jan 12, 17"
    version: v3.7.6.2
  - 
    changes: 
      - 
        text: "Changed origin to ps.pndsn.com"
        type: feature
    date: "Dec 21, 16"
    version: v3.7.6.1
  - 
    changes: 
      - 
        text: "Offers the ability to set a per message time to live in storage."
        type: feature
      - 
        text: "Find out which UUID sent the message (only avialable when debug symbol `PUBNUB_PS_V2_RESPONSE` is used)."
        type: feature
    date: "Dec 9, 16"
    version: v3.7.6
  - 
    changes: 
      - 
        text: "Windows Store Universal 10 store compatibility"
        type: improvement
      - 
        text: "Changed the JSON lib to use: https://github.com/MarkerMetro/MarkerMetro.Unity.JsonFx, as it is compatible with Windows store."
        type: improvement
      - 
        text: "BouncyCastle(http://www.bouncycastle.org/csharp/) is used for crypto functionality."
        type: improvement
    date: ~
    version: v3.7.5
  - 
    changes: 
      - 
        text: "Added a debug symbol `PUBNUB_PS_V2_RESPONSE` to enable v4 subscribe"
        type: feature
    date: "Sep 24, 16"
    version: v3.7.4
  - 
    changes: 
      - 
        text: "Fixed SetGameObject"
        type: feature
    date: ~
    version: v3.7.3
  - 
    changes: 
      - 
        text: "PubSub v2"
        type: feature
      - 
        text: "Channel Groups"
        type: feature
      - 
        text: "Message Filtering"
        type: feature
      - 
        text: "Wildcard Subscribe"
        type: feature
      - 
        text: "Code optimizations"
        type: improvement
    date: "Aug 2, 16"
    version: v3.7.2
  - 
    changes: 
      - 
        text: "A new debug symbol to reduce the usage of coroutines. Set REDUCE_PUBNUB_COROUTINES, to use the alternate logic for www coroutines used by the PubNub's SDK. When using this option it is recommended that you call TerminateCurrentSubscriberRequest when the app comes back to the foreground else an ongoing long request will wait till the timeout value to abort and reinit the request."
        type: improvement
      - 
        text: "For iOS if the value of NonSubscribeTimeout and SubscribeTimeout is greater than 59 secs, the SDK will force the value to be 59 secs."
        type: improvement
    date: "Jun 21, 16"
    version: v3.6.9.1
  - 
    changes: 
      - 
        text: "Refactored code."
        type: improvement
      - 
        text: "JSON library: the pre-compiler directives to choose between MiniJSON and JSONFx have been moved to the class JSONSerializer.cs."
        type: improvement
      - 
        text: |
            `Logging: In addition to setting the variables PubnubLogLevel = LoggingMethod.Level.Info and PubnubErrorLevel = PubnubErrorFilter.Level.Info you also need to add a "define symbol": ENABLE_PUBNUB_LOGGING for each of the platform you want to enable logging.
            
            This setting is available in the Unity Editor: File-> Build Settings -> Player Settings -> Other Settings -> Configuration -> Scripting define symbols.
            After you type ENABLE_PUBNUB_LOGGING in it do remember to press return with the focus still in the text box or your setting will not be saved.
            `
        type: improvement
      - 
        text: "Add mobile push methods."
        type: feature
      - 
        text: "Default value of SSL is now true."
        type: improvement
    date: ~
    version: v3.6.9.0
  - 
    changes: 
      - 
        text: "some fixes for subscribe request timeouts."
        type: bug
    date: ~
    version: v3.6.8.8
  - 
    changes: 
      - 
        text: "removes forceful garbage collection."
        type: improvement
    date: ~
    version: v3.6.8.7
  - 
    changes: 
      - 
        text: "Fix for \"null\" message in callback when a message contains multiple messages, one of which is of type System.Collections.Generic.Dictionary`2[System.String,System.Object]."
        type: bug
    date: ~
    version: v3.6.8.6
  - 
    changes: 
      - 
        text: "Duplicate messages on some occasions."
        type: bug
    date: ~
    version: v3.6.8.4
  - 
    changes: 
      - 
        text: "Non subscribe callbacks were not fired when called from within a callback of an earlier request."
        type: bug
    date: ~
    version: v3.6.8.3
  - 
    changes: 
      - 
        text: "Missed messages when adding a channel to multiplexed."
        type: bug
      - 
        text: "Sub timeout gets fired when in app goes in background and the request is not complete."
        type: bug
      - 
        text: "User State didn't change in some cases."
        type: bug
      - 
        text: "Multiple requests heartbeats were running."
        type: bug
    date: ~
    version: v3.6.8.1
features: 
  access: 
    - ACCESS-TOKEN-MANAGEMENT
  channel-groups: 
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  others: 
    - TELEMETRY
    - QUERY-PARAM
    - CREATE-PUSH-PAYLOAD    
  presence: 
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-SET-STATE
    - PRESENCE-GET-STATE
    - PRESENCE-HEARTBEAT
    - PRESENCE-HEARTBEAT-ON-DEMAND
    - PRESENCE-HEARTBEAT-THROTTLED    
    - PRESENCE-HERE-NOW-REFRESH
  publish: 
    - PUBLISH-STORE-FLAG
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
    - PUBLISH-POST
    - PUBLISH-ASYNC
    - PUBLISH-MESSAGE-TTL
    - PUBLISH-FIRE
  push: 
    - PUSH-ADD-DEVICE-TO-CHANNELS
    - PUSH-REMOVE-DEVICE-FROM-CHANNELS
    - PUSH-LIST-CHANNELS-FROM-DEVICE
    - PUSH-REMOVE-DEVICE
    - PUSH-TYPE-APNS
    - PUSH-TYPE-APNS2
    - PUSH-TYPE-FCM
    - PUSH-TYPE-MPNS    
  storage: 
    - STORAGE-REVERSE
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-START-END
    - STORAGE-COUNT
    - STORAGE-DELETE-MESSAGES
    - STORAGE-FETCH-MESSAGES
    - STORAGE-MESSAGE-COUNT
    - STORAGE-HISTORY-WITH-META
    - STORAGE-FETCH-WITH-META
    - STORAGE-FETCH-WITH-MESSAGE-ACTIONS
  subscribe: 
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNELS-GROUPS
    - SUBSCRIBE-WITH-TIMETOKEN
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-FILTER-EXPRESSION
    - SUBSCRIBE-PUBSUB-V2
    - SUBSCRIBE-PUBLISHER-UUID
    - SUBSCRIBE-SIGNAL-LISTENER
    - SUBSCRIBE-MEMBERSHIP-LISTENER
    - SUBSCRIBE-SPACE-LISTENER
    - SUBSCRIBE-USER-LISTENER
    - SUBSCRIBE-MESSAGE-ACTIONS-LISTENER
  objects:
    - OBJECTS-GET-USERS
    - OBJECTS-GET-USER
    - OBJECTS-CREATE-USER
    - OBJECTS-UPDATE-USER
    - OBJECTS-DELETE-USER
    - OBJECTS-GET-SPACES
    - OBJECTS-CREATE-SPACE
    - OBJECTS-GET-SPACE
    - OBJECTS-UPDATE-SPACE
    - OBJECTS-DELETE-SPACE
    - OBJECTS-GET-MEMBERSHIPS
    - OBJECTS-MANAGE-MEMBERSHIPS
    - OBJECTS-GET-MEMBERS
    - OBJECTS-MANAGE-MEMBERS
    - OBJECTS-FILTERING
  message-actions:
    - MESSAGE-ACTIONS-GET
    - MESSAGE-ACTIONS-ADD
    - MESSAGE-ACTIONS-REMOVE    
  time: 
    - TIME-TIME
  signal:
    - SIGNAL-SEND
  notify:
    - REQUEST-MESSAGE-COUNT-EXCEEDED   
name: unity
schema: 1
scm: github.com/pubnub/unity
supported-platforms: 
  - 
    editors: 
      - "Unity 5.5.1"
      - "Unity 2017.3.*"
      - "Unity 2018.*"
      - "Unity 2019.*"
    platforms: 
      - "iOS player, will require iOS 7.0 or higher."
      - "Android, OS 2.3.1 or later; ARMv7 (Cortex) CPU with NEON support or Atom CPU; OpenGL ES 2.0 or later."
      - "Windows Phone, 8.1 or later."
      - "Windows Store Apps, 8.1 or later."
      - "WebGL, Any recent desktop version of Firefox, Chrome, Edge or Safari."
      - "Windows 7+, with Graphics card DX9 (shader model 3.0) or DX11 with feature level 9.3 capabilities; and CPU SSE2 instruction set support."
      - "Ubuntu 12.04+, with Graphics card DX9 (shader model 3.0) or DX11 with feature level 9.3 capabilities; and CPU SSE2 instruction set support."
      - "Mac OS X 10.8+, with Graphics card DX9 (shader model 3.0) or DX11 with feature level 9.3 capabilities; and CPU SSE2 instruction set support."
    version: "PubNub Unity SDK"
version: v4.8.0
